#### Akash Kumar Singh

#### 19023

In [1]:
import numpy as np
import math
import random
import pygame
import gym
from gym import Env
from gym.spaces import Discrete, Box,Dict

pygame 2.1.2 (SDL 2.0.18, Python 3.8.8)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [66]:
class WarehouseEnv(Env):
    def __init__(self):
        self.action_space = Discrete(4)
        self.observation_space = Box(low=np.array([0,0]), high=np.array([6,5]),dtype= int)
        
        self.state = [1,2]
        self.target_state = [3,1]
        self.box_state = [4,3]
        
        self.action_map = {0: "UP", 1: "DOWN", 2: "LEFT", 3: "RIGHT"}
    
    def step(self, action):
        info = {}
        
        done = False
        
        is_box_located = False
    
        
        
        if self.action_map[action] == "UP":
            move_step = np.array([-1, 0])
            new_state = self.state + move_step
            
        elif self.action_map[action] == "DOWN":
            move_step = np.array([1, 0])
            new_state = self.state + move_step
            
            
        elif self.action_map[action] == "LEFT":
            move_step = np.array([0, -1])
            new_state = self.state + move_step
        
        
        elif self.action_map[action] == "RIGHT":
            move_step = np.array([0, 1])
            new_state = self.state + move_step
            
            

        if (new_state == self.box_state).all():
            is_box_located = True
            new_box_state = new_state + move_step

            
            if is_box_located:
                self.box_state = new_box_state
                
                    
        self.state = new_state          
        print(self.box_state == self.target_state)
        
        reward = 0 if np.array_equal(self.box_state, self.target_state) else -1
        
        done = True if reward ==0 else done
        
        return self.state, reward, done, info
           
        
                                     
    def render(self):
        pass

        
    def reset(self):
        self.state = [1,2]
        self.box = [4,3]
        
        return self.state
    
    
    
    
# if __name__ == "__main__":
#     env = WarehouseEnv()

#     action = env.action_space.sample()
    
#     state, reward, done, info = env.step(action)
    
#     print(env.action_map[action], state, reward, done)

In [67]:
env = WarehouseEnv()

In [68]:
env.step(1)

False


(array([2, 2]), -1, False, {})

In [69]:
env.step(1)

False


(array([3, 2]), -1, False, {})

In [70]:
env.step(1)

False


(array([4, 2]), -1, False, {})

In [71]:
env.step(3)

[False False]


(array([4, 3]), -1, False, {})

In [72]:
env.step(3)

[False False]


(array([4, 4]), -1, False, {})

In [73]:
env.step(3)

[False False]


(array([4, 5]), -1, False, {})

In [74]:
env.step(3)

[False False]


(array([4, 6]), -1, False, {})

In [75]:
env.step(3)

[False False]


(array([4, 7]), -1, False, {})

In [76]:
env.step(3)

[False False]


(array([4, 8]), -1, False, {})

In [77]:
env.step(3)

[False False]


(array([4, 9]), -1, False, {})

In [78]:
env.step(3)

[False False]


(array([ 4, 10]), -1, False, {})

In [79]:
env.box_state

array([ 4, 11])