In [1]:
import numpy as np

__Policy Iteration__

In [29]:
States = np.array(["Hostel", "Academic Building", "Canteen"])
Actions = np.array(["Eating", "AttendingClass"])
Reward = np.array([-1, 3, 1])

P = np.array(
    [
    [[0, 0, 1], [0.5, 0.5, 0]],
    [[0, 0.2, 0.8], [0, 0.7, 0.3]],
    [[0, 0, 1], [0.3, 0.6, 0.1]]    
    ])

Vs = np.zeros(3)  # stores best action value of each state
gamma = 0.9
count = 0
policy = np.random.randint(low=2, size=3)
# print(policy)# 2 bec we have 2 actions only
Va = policy.copy()   # stores best action index of each state

# The Policy iteration loop
for time in range(100):
    # Policy Evaluation
    print(time)
    V = np.zeros(3)
    for s,a in enumerate(Va):
        maxa = []
#         print (a)
#         print(s,a)
        print(P[s,a])
        t = P[s,a]
        act = 0
#         for index,element in enumerate(t):
#             if element != 0:
#                 act = act+(t[index]*(Reward[index] + gamma*V[index]))
        Va = np.argmax(np.sum(V * P, axis=2), axis=1)
#                 print(act)

#         maxa.append(act)

#         V[s] = maxa[np.argmax(maxa)]
#         print(s,a)
    
    # Policy Improvment
    Vaai = np.zeros(3)
    for st in range(len(States)):
        maxaa = []
        for aa in range(len(Actions)):
            ta = P[st][aa]
            acta = 0
            for indexi,elemente in enumerate(ta):
                if elemente != 0:
                    acta = acta+(ta[indexi]*(Reward[indexi] + gamma*V[indexi]))

            maxaa.append(acta)

        Vaai[st] = np.argmax(maxaa)
        
    if not (Va - Vaai).any():
        count += 1
        if count == 2:
            break
    else:
        count = 0

    Va = Vaai
    Vs = V
    
print(f"State : Optimal Policy, Convergence time = {time}", end="\n")
for ie, statet in enumerate(States):
    stateiv = statet
    Optimal_Action_Indexi = int(Va[ie])
    Optimal_Policy = Actions[Optimal_Action_Indexi]
    print(f"{stateiv} : {Optimal_Policy}")

0
[0. 0. 1.]
[0.  0.2 0.8]
[0. 0. 1.]
1


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

__Discuss the results obtained from policy iteration and value iteration__